### ISSUE TITLE
Contributing code to Google VR SDK

### ISSUE THREAD

**Issue by binarynate** [cwei/DaydreamController#1]
Hi, @cwei . First, I want to thank you for publishing this project on GitHub. It was a huge help in adding Daydream controller support to the iOS version of [my Unity-based app](https://www.viewport.org/).

You may be aware that the [Google VR Unity SDK](https://github.com/googlevr/gvr-unity-sdk) doesn't support Daydream controllers for iOS. When I added iOS Daydream support to my app, I implemented it as a plugin that I plan to contribute to the GVR Unity SDK once my updated app is approved in the App Store this week. Since your project served as the reference implementation for my plugin and you have a copyright included in your source, I want to ask for your blessing before I open that PR in the GVR SDK repo. My plugin uses Objective-C / C instead of Swift and exposes a different API in order to integrate more easily with Google's existing codebase, but its logic for extracting values from the BTLE payload is the same. Is it OK with you if I create that PR and credit you with the reference implementation?

**Comment by cwei** [comment]
That‘s okay for me. Good luck with your app.

**Comment by binarynate** [comment]
Thanks!
